// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  aws_app_analytics: "enable",
  aws_cognito_identity_pool_id:
    "us-east-1:d0de7acf-d7d9-4be9-8d29-b5dc7e5695c9",
  aws_cognito_region: "us-east-1",
  aws_content_delivery: "enable",
  aws_content_delivery_bucket: "club-hosting-mobilehub-1044433732",
  aws_content_delivery_bucket_region: "us-east-1",
  aws_content_delivery_cloudfront: "enable",
  aws_content_delivery_cloudfront_domain: "d2ixtpk5arcu5q.cloudfront.net",
  aws_mandatory_sign_in: "enable",
  aws_mobile_analytics_app_id: "450b045244db495d96191f0eb5888c07",
  aws_mobile_analytics_app_region: "us-east-1",
  aws_project_id: "85bf3df6-b503-4c5b-a861-867c919210b6",
  aws_project_name: "club",
  aws_project_region: "us-east-1",
  aws_resource_name_prefix: "club-mobilehub-1044433732",
  aws_sign_in_enabled: "enable",
  aws_user_pools: "enable",
  aws_user_pools_id: "us-east-1_W6wkX0t0f",
  aws_user_pools_mfa_type: "OFF",
  aws_user_pools_web_client_id: "72i87bboglcgpc9kojicg3uibn"
};

export default awsmobile;
